Update FetchDataAndImages.yml

diff --git a/.github/workflows/FetchDataAndImages.yml b/.github/workflows/FetchDataAndImages.yml
--- a/.github/workflows/FetchDataAndImages.yml
+++ b/.github/workflows/FetchDataAndImages.yml
@@ -17,37 +17,27 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Install node
-        uses: actions/setup-node@v2
-        with:
-          node-version: "14"
-
       - name: Fetch product data and download screenshots
         run: |
-          mkdir -p $DATA_DIR
-          IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
-          for LOCALE in "${LOCALE_ARRAY[@]}"; do
-            SKIP=0
-            TOTAL=0
-            ITEMS=()
-            while [ $SKIP -le $TOTAL ]; do
-              RESPONSE=$(curl -X POST \
-                -H "Content-Type: application/json" \
-                -H "Authorization: Bearer $ACCESS_TOKEN" \
-                -d '{"query":"query($locale: String,$skip: Int){productCollection(locale:$locale,where:{appStore:true},limit: '$LIMIT', skip: $skip) {total items {sys {id} key hot trademark summary overview websiteurl description screenshots distribution vcpu memory storage logo {imageurl} catalogCollection(limit:15) {items {key title catalogCollection(limit:5){items{key title}}}}}}}", "variables":{"locale":"'$LOCALE'", "skip":'$SKIP'}}' \
-                https://graphql.contentful.com/content/v1/spaces/ffrhttfighww)
-              ITEMS+=($(echo $RESPONSE | jq '.data.productCollection.items'))
-              TOTAL=$(echo $RESPONSE | jq '.data.productCollection.total')
-              SKIP=$((SKIP + LIMIT))
-            done
-            echo ${ITEMS[@]} | jq -s 'add' | \
-            sed "1s/^/const product_${LOCALE:0:2}= /" | \
-            sed "$ s/$/;/" | \
-            sed "$ a export { product_${LOCALE:0:2}};" > $DATA_DIR/product_${LOCALE:0:2}.js
-          done && mkdir -p $SCREENSHOT_DIR && IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES" && for LOCALE in "${LOCALE_ARRAY[@]}"; do
-            chmod u+r ${DATA_DIR}/product_${LOCALE:0:2}.js
-            jq -r '.[].screenshots[].value' <(node -e "const fs = require('fs'); const product = JSON.parse(fs.readFileSync(`${DATA_DIR}/product_${LOCALE:0:2}.js`, 'utf8')); console.log(JSON.stringify(product));") |  xargs -I {} -P 8 bash -c 'url={}; url=${url/https:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com};value=${url#*DocsPicture/}; value=${value%/*}; lang=${value%%/*}; mkdir -p $SCREENSHOT_DIR/$lang; FILENAME=$(basename $url); wget --tries=3 --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 $url -O $SCREENSHOT_DIR/$lang/$FILENAME || echo $url >> $SCREENSHOT_DIR/Error.log'
-          done
+          mkdir -p $SCREENSHOT_DIR && IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES" && for LOCALE in "${LOCALE_ARRAY[@]}"; do
+             SKIP=0
+             TOTAL=0
+             ITEMS=()
+             while [ $SKIP -le $TOTAL ]; do
+               RESPONSE=$(curl -X POST \
+                 -H "Content-Type: application/json" \
+                 -H "Authorization: Bearer $ACCESS_TOKEN" \
+                 -d '{"query":"query($locale: String,$skip: Int){productCollection(locale:$locale,where:{appStore:true},limit: '$LIMIT', skip: $skip) {total items {sys {id} key hot trademark summary overview websiteurl description screenshots distribution vcpu memory storage logo {imageurl} catalogCollection(limit:15) {items {key title catalogCollection(limit:5){items{key title}}}}}}}", "variables":{"locale":"'$LOCALE'", "skip":'$SKIP'}}' \
+                 https://graphql.contentful.com/content/v1/spaces/ffrhttfighww)
+               ITEMS+=($(echo $RESPONSE | jq '.data.productCollection.items'))
+               TOTAL=$(echo $RESPONSE | jq '.data.productCollection.total')
+               SKIP=$((SKIP + LIMIT))
+             done
+             # 下载图片
+             echo ${ITEMS[@]} | jq -r '.[].screenshots[].value' |  xargs -I {} -P 8 bash -c 'url={}; url=${url/https:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com};value=${url#*DocsPicture/}; value=${value%/*}; lang=${value%%/*}; mkdir -p $SCREENSHOT_DIR/$lang; FILENAME=$(basename $url); wget --tries=3 --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 $url -O $SCREENSHOT_DIR/$lang/$FILENAME || echo $url >> $SCREENSHOT_DIR/Error.log'
+             # 写入文件
+             echo ${ITEMS[@]} | awk -v locale=${LOCALE:0:2} -v data_dir=$DATA_DIR 'BEGIN{RS="}";FS="{";ORS="}";OFS="{";print "const product_"locale"= ["} {if(NR>1)print $0} END{print "];\nexport { product_"locale" };" > data_dir"/product_"locale".js"}'
+           done
 
       - name: Commit and push changes
         uses: stefanzweifel/git-auto-commit-action@v4
