Update FetchDataAndImages.yml

diff --git a/.github/workflows/FetchDataAndImages.yml b/.github/workflows/FetchDataAndImages.yml
--- a/.github/workflows/FetchDataAndImages.yml
+++ b/.github/workflows/FetchDataAndImages.yml
@@ -49,9 +49,8 @@ jobs:
                TOTAL=$(echo $RESPONSE | jq '.data.productCollection.total')
                SKIP=$((SKIP + LIMIT))
              done
-             echo ${ITEMS[@]}
              # 下载图片
-             echo ${ITEMS[@]} | jq '.[].screenshots[].value' |  xargs -I {} -- bash -c "url={}; printf \"%s\\n\" \"url=$url\"; url=${url/https:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com}; mkdir -p $SCREENSHOT_DIR/${LOCALE:0:2}; FILENAME=$(basename \"$url\"); wget --tries=3 --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 \"$url\" -O $SCREENSHOT_DIR/${LOCALE:0:2}/$FILENAME || echo \"$url\" >> $SCREENSHOT_DIR/Error.log"
+             echo ${ITEMS[@]} | jq -v '.[].screenshots[].value' |  xargs -I {} bash -c "url={}; printf \"%s\\n\" \"url=$url\"; url=${url/https:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com}; mkdir -p $SCREENSHOT_DIR/${LOCALE:0:2}; FILENAME=$(basename \"$url\"); wget --tries=3 --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 \"$url\" -O $SCREENSHOT_DIR/${LOCALE:0:2}/$FILENAME || echo \"$url\" >> $SCREENSHOT_DIR/Error.log"
              # 写入文件
              echo ${ITEMS[@]} | jq -s 'add' | \
              sed "1s/^/const product_${LOCALE:0:2}= /" | \
