Update FetchDataAndImages.yml

diff --git a/.github/workflows/FetchDataAndImages.yml b/.github/workflows/FetchDataAndImages.yml
--- a/.github/workflows/FetchDataAndImages.yml
+++ b/.github/workflows/FetchDataAndImages.yml
@@ -50,7 +50,9 @@ jobs:
                SKIP=$((SKIP + LIMIT))
              done
              # 下载图片
-             echo ${ITEMS[@]} | jq --raw-output '.[].screenshots[].value' | xargs -P 8 -n 1 bash -c 'url=$1; echo "url=$url"; mkdir -p $SCREENSHOT_DIR/${LOCALE:0:2}; curl -o $SCREENSHOT_DIR/${LOCALE:0:2}/$(basename $url) $url || echo $url >> $SCREENSHOT_DIR/Error.log' _
+             DIR="$SCREENSHOT_DIR/${LOCALE:0:2}"
+             mkdir -p "$DIR"
+             echo ${ITEMS[@]} | jq --raw-output '.[].screenshots[].value' | xargs -P 8 -n 1 bash -c 'url=$1; echo "url=$url"; curl -o $DIR/$(basename $url) $url || echo $url >> $SCREENSHOT_DIR/Error.log' _
 
              # 写入文件
              echo ${ITEMS[@]} | jq -s 'add' | \
