Update FetchDataAndImages.yml

diff --git a/.github/workflows/FetchDataAndImages.yml b/.github/workflows/FetchDataAndImages.yml
--- a/.github/workflows/FetchDataAndImages.yml
+++ b/.github/workflows/FetchDataAndImages.yml
@@ -50,8 +50,12 @@ jobs:
                SKIP=$((SKIP + LIMIT))
              done
              # 下载图片
-             echo ${ITEMS[@]} | jq '.[].screenshots[].value' | while read url; do url=${url/https:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com} mkdir -p $SCREENSHOT_DIR/${LOCALE:0:2} FILENAME=$(basename "$url") wget --tries=3 --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 "$url" -O $SCREENSHOT_DIR/${LOCALE:0:2}/$FILENAME || echo "$url" >> $SCREENSHOT_DIR/Error.log done
-            
+             echo ${ITEMS[@]} | jq '.[].screenshots[].value' | while read url; do 
+              url=${url/https:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com}
+              mkdir -p $SCREENSHOT_DIR/${LOCALE:0:2}
+              FILENAME=$(basename "$url")
+              wget --tries=3 --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 "$url" -O $SCREENSHOT_DIR/${LOCALE:0:2}/$FILENAME || echo "$url" >> $SCREENSHOT_DIR/Error.log
+             done
              # 写入文件
              echo ${ITEMS[@]} | jq -s 'add' | \
              sed "1s/^/const product_${LOCALE:0:2}= /" | \
