Update FetchDataAndImages.yml
修改logo下载目录：同时放到appstore和myapps下
修改screenshot的下载方式：同时下载8张图

diff --git a/.github/workflows/FetchDataAndImages.yml b/.github/workflows/FetchDataAndImages.yml
--- a/.github/workflows/FetchDataAndImages.yml
+++ b/.github/workflows/FetchDataAndImages.yml
@@ -9,8 +9,9 @@ jobs:
       ACCESS_TOKEN: ${{ secrets.CONTENTFUL_GRAPHQLTOKEN }}
       LOCALES: "en-US,zh-CN"
       DATA_DIR: "plugins/appstore/build/static/data/json"
-      LOGO_DIR: "plugins/appstore/build/static/data/logo/"
-      SCREENSHOT_DIR: "plugins/appstore/build/static/data/screenshot/"
+      APPSTORE_LOGO_DIR: "plugins/appstore/build/static/data/logo/"
+      MYAPPS_LOGO_DIR: "plugins/myapps/build/static/data/logo/"
+      SCREENSHOT_DIR: "plugins/appstore/build/static/data/screenshot"
       LIMIT: 100
 
     steps:
@@ -55,14 +56,14 @@ jobs:
         run: ./ossutil64 config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }}
 
       - name: Download logos from oss
-        run: ./ossutil64 cp oss://libs-websoft9-com/Websoft9/logo/product/ $LOGO_DIR -r --update
+        run: ./ossutil64 cp oss://libs-websoft9-com/Websoft9/logo/product/ $APPSTORE_LOGO_DIR -r --update && ./ossutil64 cp oss://libs-websoft9-com/Websoft9/logo/product/ $MYAPPS_LOGO_DIR -r --update
 
       - name: Download screenshots from oss
         run: |
           mkdir -p $SCREENSHOT_DIR
           IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
           for LOCALE in "${LOCALE_ARRAY[@]}"; do
-            jq -r '.[].screenshots[].value' $DATA_DIR/product_$LOCALE.json |  xargs -I {} bash -c 'url={}; url=${url/https:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com}; url=${url/http:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com}; value=${url#*DocsPicture/}; value=${value%/*}; lang=${value%%/*}; mkdir -p $SCREENSHOT_DIR/$lang; FILENAME=$(basename $url); wget --tries=3 --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 $url -O $SCREENSHOT_DIR/$lang/$FILENAME || echo $url >> $SCREENSHOT_DIR/Error.log'
+            jq -r '.[].screenshots[].value' $DATA_DIR/product_$LOCALE.json |  xargs -I {} -P 8 bash -c 'url={}; url=${url/https:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com}; url=${url/http:\/\/libs.websoft9.com/http:\/\/libs.websoft9.com}; value=${url#*DocsPicture/}; value=${value%/*}; lang=${value%%/*}; mkdir -p $SCREENSHOT_DIR/$lang; FILENAME=$(basename $url); wget --tries=3 --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 $url -O $SCREENSHOT_DIR/$lang/$FILENAME || echo $url >> $SCREENSHOT_DIR/Error.log'
           done
 
       - name: Commit and push changes
