Update FetchDataAndImages.yml

diff --git a/.github/workflows/FetchDataAndImages.yml b/.github/workflows/FetchDataAndImages.yml
--- a/.github/workflows/FetchDataAndImages.yml
+++ b/.github/workflows/FetchDataAndImages.yml
@@ -47,7 +47,12 @@ jobs:
                SKIP=$((SKIP + LIMIT))
              done
              # 下载图片
-             echo "${ITEMS[@]}" | jq -r '.screenshots[].value' | xargs -n 1 -P 10 sh -c 'wget -O "$SCREENSHOT_DIR/${1%%-*}/${0##*/}" $0' $LOCALE
+             echo ${ITEMS[@]} | jq '.screenshots[]?.value' | while read url; do
+              url=$(echo $url | sed 's/"//g')
+              mkdir -p $SCREENSHOT_DIR/${LOCALE:0:2}
+              FILENAME=$(basename "$url")
+              wget -t 0 "$url" -O $SCREENSHOT_DIR/${LOCALE:0:2}/$FILENAME || echo "$url" >> $SCREENSHOT_DIR/Error.log
+             done
              # 写入文件
              echo ${ITEMS[@]} | jq -s '.' > $DATA_DIR/product_${LOCALE:0:2}.json
            done
