Update FetchDataAndImages.yml

diff --git a/.github/workflows/FetchDataAndImages.yml b/.github/workflows/FetchDataAndImages.yml
--- a/.github/workflows/FetchDataAndImages.yml
+++ b/.github/workflows/FetchDataAndImages.yml
@@ -1,4 +1,4 @@
-name: Relese Plugin-Appstore To Azure
+name: Fetch Contentful Data and Oss Images
 
 on: workflow_dispatch
 
@@ -6,45 +6,67 @@ jobs:
   fetch-data:
     runs-on: ubuntu-latest
     env:
-      CI: false
+      ACCESS_TOKEN: ${{ secrets.CONTENTFUL_GRAPHQLTOKEN }}
+      LOCALES: "en-US,zh-CN"
+      DATA_DIR: "data/json"
+      APPSTORE_LOGO_DIR: "data/logos"
+      SCREENSHOT_DIR: "data/screenshots"
+      LIMIT: 100
 
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: 20.2.0
-
-      - name: Install dependencies
-        run: npm install
-
-      - name: Build
-        run: yarn build
-
-      - name: Copy Data、Logos、Screenshots To Plugin
-        run: cp -R data/  build/static/
-
-      - name: Read Plugin Version
-        id: read-version
+      - name: Fetch catalog data from contentful graphql
         run: |
-          version=$(jq -r '.Version' websoft9.json)
-          echo "::set-output name=version::$version"
+          mkdir -p $DATA_DIR
+          IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
+          for LOCALE in "${LOCALE_ARRAY[@]}"; do
+            curl -X POST \
+              -H "Content-Type: application/json" \
+              -H "Authorization: Bearer $ACCESS_TOKEN" \
+              -d '{"query":"query($locale: String){catalog(id: \"2Yp0TY3kBHgG6VDjsHZNpK\",locale:$locale) {linkedFrom(allowedLocales:[\"en-US\"]) {catalogCollection(limit:20) {items {key position title linkedFrom(allowedLocales:[\"en-US\"]) {catalogCollection(limit:20) {items {key title position}}}}}}}}","variables":{"locale":"'$LOCALE'"}}' \
+              https://graphql.contentful.com/content/v1/spaces/ffrhttfighww | \
+              jq '.data.catalog.linkedFrom.catalogCollection.items' > $DATA_DIR/catalog_${LOCALE:0:2}.json
+          done
 
-      - name: Create Zip Archive
+      - name: Fetch product data and download screenshots
         run: |
-          zip -r appstore-${{ steps.read-version.outputs.version }}.zip build/
+          mkdir -p $SCREENSHOT_DIR && IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES" && for LOCALE in "${LOCALE_ARRAY[@]}"; do
+             SKIP=0
+             TOTAL=0
+             ITEMS=()
+             while [ $SKIP -le $TOTAL ]; do
+               RESPONSE=$(curl -X POST \
+                 -H "Content-Type: application/json" \
+                 -H "Authorization: Bearer $ACCESS_TOKEN" \
+                 -d '{"query":"query($locale: String,$skip: Int){productCollection(locale:$locale,where:{appStore:true},limit: '$LIMIT', skip: $skip) {total items {sys {id} key hot trademark summary overview websiteurl description screenshots distribution vcpu memory storage logo {imageurl} catalogCollection(limit:15) {items {key title catalogCollection(limit:5){items{key title}}}}}}}", "variables":{"locale":"'$LOCALE'", "skip":'$SKIP'}}' \
+                 https://graphql.contentful.com/content/v1/spaces/ffrhttfighww)
+               ITEMS+=($(echo $RESPONSE | jq '.data.productCollection.items[]'))
+               TOTAL=$(echo $RESPONSE | jq '.data.productCollection.total')
+               SKIP=$((SKIP + LIMIT))
+             done
+             # 下载图片
+             echo ${ITEMS[@]} | jq '.screenshots[]?.value' | while read url; do
+              url=$(echo $url | sed 's/"//g')
+              mkdir -p $SCREENSHOT_DIR/${LOCALE:0:2}
+              FILENAME=$(basename "$url")
+              wget -t 0 "$url" -O $SCREENSHOT_DIR/${LOCALE:0:2}/$FILENAME || echo "$url" >> $SCREENSHOT_DIR/Error.log
+             done
+             # 写入文件
+             echo ${ITEMS[@]} | jq -s '.' > $DATA_DIR/product_${LOCALE:0:2}.json
+           done
 
-      - name: Upload To Azure
-        uses: bacongobbler/azure-blob-storage-upload@main
-        with:
-          source_dir: ./appstore-${{ steps.read-version.outputs.version }}.zip
-          container_name: relese
-          connection_string: ${{ secrets.AZURE_STORAGE_ARTIFACT }}
-          extra_args: "--destination-path ./websoft9/plugin"
-          overwrite: true
+      - name: Install ossutil
+        run: |
+          wget http://gosspublic.alicdn.com/ossutil/1.7.6/ossutil64
+          chmod 755 ossutil64
+      - name: Configure ossutil
+        run: ./ossutil64 config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }}
+
+      - name: Download logos from oss
+        run: ./ossutil64 cp oss://libs-websoft9-com/Websoft9/logo/product/ $APPSTORE_LOGO_DIR -r --update
 
       - name: Commit and push changes
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
-          commit_message: build plugin
+          commit_message: Update data 、logos、screenshots
